### ISSUE TITLE
qpm install issue

### ISSUE THREAD

**Issue by gametack** [benlau/fontawesome.pri#1]
Installing font.awesome.pri@1.0.0
QPM: 2017/01/06 05:19:56 ERROR: GetFileAttributesEx C:\Users\manny\Desktop\progr
amming\temp\untitled12\vendor\benlau-fontawesome.pri-57e5227\scripts\qpm.json: T
he system cannot find the file specified.

**Comment by benlau** [comment]
hi @gametack,

Probably you could fix this problem by installing the latest version of qpm. 

Reference of the bug report:
https://github.com/Cutehacks/qpm/issues/24
